# Generated by Django 4.2.6 on 2023-11-19 21:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='1234567890', max_length=128, region=None)),
                ('is_Email_Verified', models.BooleanField(default=False)),
                ('is_Phone_Verified', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('INTERMEDIATE', 'Intermediate')], default='ADMIN', max_length=50, verbose_name='Type')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_ID', models.IntegerField(blank=True, default=0, null=True)),
                ('doctor_Intermediate_ID', models.IntegerField(blank=True, default=0, null=True)),
                ('meeting_Date_Time', models.DateTimeField(default=datetime.datetime(2023, 11, 19, 15, 42, 11, 611939, tzinfo=datetime.timezone.utc), verbose_name='Meeting Date and Time')),
                ('meeting_Type', models.CharField(choices=[('CHAT', 'Chat'), ('VIDEOCALL', 'Videocall')], default='CHAT', max_length=50, verbose_name='Meeting type')),
                ('disease', models.TextField(null=True, verbose_name='Information about disease')),
                ('video_URL', models.URLField(blank=True, null=True, verbose_name='Meet link')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.TextField(max_length=200)),
                ('specialization', models.CharField(choices=[('CARDIOLOGIST', 'Cardiologist'), ('DERMATOLOGIST', 'Dermatologist'), ('ORTHOPEDIC', 'Orthopedic'), ('GYNECOLOGIST', 'Gynecologist'), ('NEUROLOGIST', 'Neurologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENT', 'Ent'), ('GASTROENTEROLOGIST', 'Gastroenterologist'), ('PSYCHIATRIST', 'Psychiatrist'), ('ENDOCRINOLOGIST', 'Endocrinologist')], max_length=20, verbose_name='Speciality')),
                ('is_Free', models.BooleanField(verbose_name='Is the doctor free for a meeting?')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
            },
            bases=('healthcare.newuser',),
        ),
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Intermediate person',
                'verbose_name_plural': 'Intermediate people',
            },
            bases=('healthcare.newuser',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('blood_Group', models.CharField(default='Blood group not mentioned.', max_length=4, verbose_name='Blood group')),
                ('ailments', models.CharField(default='None', max_length=500, verbose_name='Ailments')),
                ('severity', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('SEVERE', 'Severe')], default='MILD', max_length=20, null=True, verbose_name='Severity')),
                ('disease', models.TextField(blank=True, null=True, verbose_name='Information about disease')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='FEMALE', max_length=20, null=True, verbose_name='Gender')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
            bases=('healthcare.newuser',),
        ),
    ]
