# Generated by Django 4.2.6 on 2023-11-19 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 13, 29, 27, 429699, tzinfo=datetime.timezone.utc), verbose_name='Meeting Date and Time'),
        ),
    ]
