# Generated by Django 4.2.6 on 2023-10-29 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 9, 22, 16, 90548, tzinfo=datetime.timezone.utc), verbose_name='Meeting Date and Time'),
        ),
    ]
