# Generated by Django 4.2.6 on 2023-10-25 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_newuser_firstname_newuser_lastname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
