# Generated by Django 4.2.6 on 2023-10-25 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_alter_doctor_options_alter_patient_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='lastname',
        ),
    ]
