# Generated by Django 4.2.6 on 2023-10-25 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_remove_newuser_firstname_remove_newuser_lastname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='newuser',
            managers=[
            ],
        ),
    ]
