# Generated by Django 4.2.6 on 2023-10-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0007_alter_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_Email_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_Phone_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
