# Generated by Django 4.2.6 on 2023-10-27 11:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0008_patient_is_email_verified_patient_is_phone_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_Email_Verified',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_Phone_Verified',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_Email_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='is_Phone_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='123456789', max_length=128, region=None),
        ),
    ]
