# Generated by Django 4.2.6 on 2023-10-27 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0009_remove_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediate',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('about', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Intermediate person',
                'verbose_name_plural': 'Intermediate people',
            },
            bases=('healthcare.newuser',),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='type',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('PATIENT', 'Patient'), ('ADMIN', 'Admin'), ('INTERMEDIATE', 'Intermediate')], default='ADMIN', max_length=50, verbose_name='Type'),
        ),
    ]
