# Generated by Django 4.2.6 on 2023-10-29 10:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0010_intermediate_alter_newuser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='1234567890', max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_Date', models.DateField(verbose_name='Meeting Date')),
                ('meeting_Time', models.TimeField(verbose_name='Meeting Time')),
                ('meeting_Type', models.CharField(choices=[('CHAT', 'Chat'), ('VIDEOCALL', 'Videocall')], default='CHAT', max_length=50, verbose_name='Meeting type')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare.doctor')),
                ('intermediate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare.intermediate')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='healthcare.patient')),
            ],
        ),
    ]
