# Generated by Django 4.2.6 on 2023-10-29 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0011_alter_newuser_phone_number_appointments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
