# Generated by Django 4.2.6 on 2023-10-29 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0012_delete_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='meeting_Date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='meeting_Time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='metting_Date_Time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Meeting Date and Time'),
        ),
    ]
