# Generated by Django 4.2.6 on 2023-10-29 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0013_remove_appointments_meeting_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='metting_Date_Time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Meeting Date and Time'),
        ),
    ]
