# Generated by Django 4.2.6 on 2023-10-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0014_alter_appointments_metting_date_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
    ]
