# Generated by Django 4.2.6 on 2023-10-29 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0015_rename_appointments_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='metting_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 5, 35, 35, 595711, tzinfo=datetime.timezone.utc), verbose_name='Meeting Date and Time'),
        ),
    ]
