# Generated by Django 4.2.6 on 2023-10-29 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0017_alter_appointment_metting_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='severity',
            field=models.CharField(choices=[('MILD', 'Mild'), ('SEVERE', 'Severe')], default='MILD', max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='metting_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 7, 10, 47, 835921, tzinfo=datetime.timezone.utc), verbose_name='Meeting Date and Time'),
        ),
    ]
