# Generated by Django 4.2.6 on 2023-10-29 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0018_patient_severity_alter_appointment_metting_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='metting_Date_Time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='meeting_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 7, 12, 32, 425433, tzinfo=datetime.timezone.utc), verbose_name='Meeting Date and Time'),
        ),
    ]
