# Generated by Django 4.2.6 on 2023-10-29 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0019_remove_appointment_metting_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='meeting_Date_Time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 7, 45, 8, 460146, tzinfo=datetime.timezone.utc), verbose_name='Meeting Date and Time'),
        ),
    ]
