# Generated by Django 4.2.6 on 2023-10-24 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='room_Name',
            new_name='room_name',
        ),
    ]
