# Generated by Django 4.2.6 on 2023-10-27 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_roommember_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='user',
        ),
    ]
